#!/bin/bash
set -euo pipefail

reveal_bin="node_modules/.bin/reveal-md"

talk:new() {
    talk_name="$2"
    if [[ -n "$talk_name" ]]; then
        echo $talk_name
        talk_dir="src/$talk_name"
        talk_file="$talk_dir/talk.md"

        mkdir -p "$talk_dir"
        cp talk.md "$talk_file"
        sed -i "s/{{TITLE}}/$talk_name/g" "$talk_file"
    fi
}

talk:done() {
    talk_name="$2"
    talk_file="src/$talk_name"
    if [[ -n "$talk_file" ]]; then
        ln -s "../$talk_file" "done/$talk_name"
    fi
}

talk:compile() {
    talk_path="$2"
    talk_name=$(echo $talk_path | cut -d '/' -f 2)

    output_dir="dist"
    output_talk="$output_dir/$talk_name"
    mkdir -p $output_dir

    $reveal_bin "$talk_path" --print "$output_talk" --theme league
}

talks:todo() {
    for talk_todo in $(ls src/); do
        if [[ ! -e "done/$talk_todo" ]]; then
            echo "$talk_todo"
        fi
    done
}

talks:present() {
    $reveal_bin src --host 0.0.0.0 --theme league
}

talks:compile:done() {
    for talk_done_path in $(find -L done -iname '*.md'); do
        talk:compile _ $talk_done_path
    done
}

"$1" "$@"
help() {
    cat "$0" | grep "^.*() {$" | cut -d "(" -f1
}

if [ ! -z ${1:-} ]; then
    "$1" "$@"
else
    help
fi
